server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: "UTF-8"
      force: true

spring:
  application:
    name: "crediya-autenticacion"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:crediya_autenticacion}
    schema: public
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}

validation:
  salary:
    max: 15000000