package co.pragma.error;

public enum ErrorCode {
    EMAIL_ALREADY_REGISTERED,
    DOCUMENTO_ALREADY_REGISTERED,
    SALARIO_OUT_OF_RANGE,
    USUARIO_NOT_FOUND,
    CREDENCIALES_INVALIDAS,
    ROL_NOT_FOUND,
    FORBIDDEN,
    TECHNICAL_ERROR,
    INVALID_INPUT,
    INVALID_REQUEST,
    INTERNAL_SERVER_ERROR;
}
